valor = int(input("Digite um valor de 1 a 10: "))
if valor == 1:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 2:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 3:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 4:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 5:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 6:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 7:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 8:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 9:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
elif valor == 10:
 print(f" 1 x {valor} = " ,(valor * 1))
 print(f" 1 x {valor} = ", (valor * 2))
 print(f" 1 x {valor} = ", (valor * 3))
 print(f" 1 x {valor} = ", (valor * 4))
 print(f" 1 x {valor} = " ,(valor * 5))
 print(f" 1 x {valor} = " ,(valor * 6))
 print(f" 1 x {valor} = " ,(valor * 7))
 print(f" 1 x {valor} = " ,(valor * 8))
 print(f" 1 x {valor} = " ,(valor * 9))
 print(f" 1 x {valor} = " ,(valor * 10))
else:
 print(f"Você digitou um valor inválido")
